### ISSUE TITLE
No feedback from bluetooth scan

### ISSUE THREAD

**Issue by Pawel-Kica** [friyiajr/BleRTKSample#1]
Hi @friyiajr, I found this repository thanks to your youtube channel which covers in detail the beginner (for me 😅) and advanced stuff about React-Native and Bluetooth. The first thing I wanted to emphasise - you present very solid knowledge on your channel, which even nowadays is not "easy" to find on the Internet - so I and I believe many others really appreciate your work - Thank You for that 👍 

Unfortunately I ran into the following problem - I'm trying to do the simplest thing, which is to request for Bluetooth permissions on Android using the expo project - and when I run the project with `npx expo start` and access the app via 'expo go' on my phone I see that permission request (in this example for BLUETOOTH_SCAN) does not allow the app to continue running? I couldn't get executed "Step 2" console.log - always gets stuck at the request level

![image](https://github.com/friyiajr/BleRTKSample/assets/89777457/74456e89-0702-4ce3-98df-e881be1ed6f9)

Do you think you can help with this issue?

**Comment by friyiajr** [comment]
Hi, please don't use Expo Go. In the previous video in this series I use the following two commands to build the app

* `npx expo run:android --device`
* `npx expo run:ios --device`

The commands build a custom expo client on the developer's hardware. Expo Go will not work for this project. You need to use the custom Expo Client. For more explanation please see the first video in the series:

https://youtu.be/UuHLPsjp6fM
